In [1]:
import pandas as pd

df = pd.read_csv('..\\data\\raw\\data.csv')

print(df.shape)
print(df.columns)

df.head(10)

(51, 2)
Index(['text', 'category'], dtype='object')

                                                text      category
0  Pandas is a powerful library for data manipula...        python
1  Pandas is a powerful library for data manipula...        python
2                                                NaN        python
3                                        Short text.       general
4    Machine   learning   models   are   only   a...  data_science
5                                   Git is for code.        devops
6  Data cleaning is the most important step in an...  data_science
7  Scikit-learn provides simple and efficient too...        python
8  Scikit-learn provides simple and efficient too...        python
9                                                NaN  data_science

In [2]:
print(df.isna().sum)

<bound method DataFrame.sum of      text  category
0   False     False
1   False     False
2    True     False
3   False     False
4   False     False
5   False     False
6   False     False
7   False     False
8   False     False
9    True     False
10  False     False
11  False     False
12  False     False
13  False     False
14  False     False
15  False     False
16  False     False
17  False     False
18  False     False
19  False     False
20  False     False
21  False     False
22  False     False
23   True     False
24  False     False
25  False     False
26  False     False
27  False     False
28  False     False
29  False     False
30  False     False
31  False     False
32  False     False
33  False     False
34  False     False
35  False     False
36  False     False
37  False     False
38  False     False
39  False     False
40  False     False
41  False     False
42  False     False
43  False     False
44  False     False
45  False     False
46  False     False
47  False     False
48  False     False
49  False     False
50  False     False>

In [4]:
print(df["text"].duplicated().sum())

5

In [5]:
df = df.dropna(subset=["text"])
print(df.shape)

(48, 2)

In [7]:
df["text"] = df["text"].str.strip().str.replace(r"\s+", " ", regex=True)
df.head(10)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
1   Pandas is a powerful library for data manipula...        python
3                                         Short text.       general
4   Machine learning models are only as good as th...  data_science
5                                    Git is for code.        devops
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
8   Scikit-learn provides simple and efficient too...        python
10                                         Too short.       general
11  Feature engineering is the process of using do...  data_science

In [8]:
df = df[df["text"].str.len() > 50]
df.head(10)

                                                 text      category
0   Pandas is a powerful library for data manipula...        python
1   Pandas is a powerful library for data manipula...        python
4   Machine learning models are only as good as th...  data_science
6   Data cleaning is the most important step in an...  data_science
7   Scikit-learn provides simple and efficient too...        python
8   Scikit-learn provides simple and efficient too...        python
11  Feature engineering is the process of using do...  data_science
12  Neural networks are inspired by the biological...  data_science
13  Jupyter Notebook is an open-source web applica...        python
14  Overfitting occurs when a model learns the det...  data_science